export const DISABLE_BUTTONS = 'APP/DISABLE_BUTTONS'
export const ENABLE_BUTTONS = 'APP/ENABLE_BUTTONS'
export const FETCH_RATES = 'CONVERTER/FETCH_RATES'
export const HANDLE_CHANGE = 'CONVERTER/HANDLE_CHANGE'
